# Generated by Django 5.0.2 on 2024-02-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nntname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntt',
            name='nnt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.nntname'),
            preserve_default=False,
        ),
    ]
