# Generated by Django 5.0.2 on 2024-02-26 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ntt_nnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tuman shaxar nomlari',
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.CharField(max_length=255)),
                ('chairman', models.CharField(max_length=255)),
                ('inspector', models.CharField(max_length=255)),
                ('assistant', models.CharField(max_length=255)),
                ('youth_leader', models.CharField(max_length=255)),
                ('women_activists', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cityname')),
            ],
            options={
                'verbose_name_plural': 'MFY haqida',
            },
        ),
    ]
