# Generated by Django 5.0.2 on 2024-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_normativhujjat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityname',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityname',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityname',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nntname',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nntname',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nntname',
            name='name_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='number_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='number_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='number_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normativhujjat',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='address_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='direction_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='direction_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='direction_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='director_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='director_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='director_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='name_en',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='name_ru',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='name_uz',
            field=models.CharField(max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='projects_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='projects_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='projects_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='purpose_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='purpose_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ntt',
            name='purpose_uz',
            field=models.TextField(null=True),
        ),
    ]
