# Generated by Django 5.0.2 on 2024-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_body_en_blog_body_ru_blog_body_uz_blog_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
