# Generated by Django 5.0.2 on 2024-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_oav'),
    ]

    operations = [
        migrations.AddField(
            model_name='oav',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oav',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oav',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oav',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oav',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oav',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
