# Generated by Django 5.0.2 on 2024-05-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blog_body_alter_blog_body_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streets',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='chairman',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='women_activists',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='youth_leader',
        ),
        migrations.AddField(
            model_name='streets',
            name='area',
            field=models.CharField(default=1, max_length=255, verbose_name='Hududi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streets',
            name='mfy_count',
            field=models.CharField(default=1, max_length=255, verbose_name='MFY lar soni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cityname',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Shaxar, tuman nomi'),
        ),
        migrations.AlterField(
            model_name='cityname',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Shaxar, tuman nomi'),
        ),
        migrations.AlterField(
            model_name='cityname',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Shaxar, tuman nomi'),
        ),
        migrations.AlterField(
            model_name='cityname',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Shaxar, tuman nomi'),
        ),
        migrations.AlterField(
            model_name='nntname',
            name='name',
            field=models.CharField(max_length=500, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='nntname',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='nntname',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='nntname',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='address',
            field=models.TextField(verbose_name='Manzil va tel raqam'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Manzil va tel raqam'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil va tel raqam'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil va tel raqam'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='direction',
            field=models.TextField(verbose_name='Yonalishi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='direction_en',
            field=models.TextField(null=True, verbose_name='Yonalishi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='direction_ru',
            field=models.TextField(null=True, verbose_name='Yonalishi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='direction_uz',
            field=models.TextField(null=True, verbose_name='Yonalishi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='director',
            field=models.CharField(max_length=255, verbose_name='Direktor FISH'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='director_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Direktor FISH'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='director_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Direktor FISH'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='director_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Direktor FISH'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='image',
            field=models.ImageField(upload_to='ntt/director', verbose_name='NNT rahbarini rasmi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='membership',
            field=models.CharField(max_length=550, verbose_name='Azoligi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='name',
            field=models.CharField(max_length=550, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='name_en',
            field=models.CharField(max_length=550, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='name_ru',
            field=models.CharField(max_length=550, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='name_uz',
            field=models.CharField(max_length=550, null=True, verbose_name='NNT nomi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='nnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nntname', verbose_name='NNT'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='projects',
            field=models.TextField(verbose_name='Loyihalari'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='projects_en',
            field=models.TextField(null=True, verbose_name='Loyihalari'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='projects_ru',
            field=models.TextField(null=True, verbose_name='Loyihalari'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='projects_uz',
            field=models.TextField(null=True, verbose_name='Loyihalari'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='purpose',
            field=models.TextField(verbose_name='Maqsadi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='purpose_en',
            field=models.TextField(null=True, verbose_name='Maqsadi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='purpose_ru',
            field=models.TextField(null=True, verbose_name='Maqsadi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='purpose_uz',
            field=models.TextField(null=True, verbose_name='Maqsadi'),
        ),
        migrations.AlterField(
            model_name='ntt',
            name='register_number',
            field=models.CharField(max_length=550, verbose_name='Royxatdan otgan raqami'),
        ),
        migrations.AlterField(
            model_name='streets',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cityname', verbose_name='Shaxar tuman nomini tanlang'),
        ),
        migrations.AlterField(
            model_name='streets',
            name='population',
            field=models.CharField(max_length=255, verbose_name='Aholi soni'),
        ),
    ]
